name: main
on:
  workflow_dispatch:

jobs:
  EnvSetup:
    environment: development
    name: Setup Dynamic Environment Variables
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.set-output-defaults.outputs.url }}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |
          echo "url=https://myuerlher.com" >> $GITHUB_OUTPUT
      - name: wait a bunch
        id: set-output-defaults
        run: |
          sleep 20
      - name: set outputs with default values
        id: set-output-defaults
        run: |
          sleep 20
  invoke-workflow:
    needs: EnvSetup
    uses: ./.github/workflows/sub.yml
    with:
      url: ${{needs.EnvSetup.outputs.url}}